fixing deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,11 +33,25 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
-          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
-          docker build --compress -t ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA .
-          docker push ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA
-          docker build --compress -t ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA proxy/
-          docker push ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA
+          # aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
+          # docker build --compress -t ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA .
+          # docker push ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA
+          # docker build --compress -t ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA proxy/
+          # docker push ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA
+          echo "Starting Docker login..."
+          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com" || { echo 'Docker login failed'; exit 1; }
+          
+          echo "Building app Docker image..."
+          docker build --compress -t "${{ vars.ECR_REPO_APP }}:$GITHUB_SHA" . || { echo 'Docker build for app failed'; exit 1; }
+          
+          echo "Pushing app Docker image..."
+          docker push "${{ vars.ECR_REPO_APP }}:$GITHUB_SHA" || { echo 'Docker push for app failed'; exit 1; }
+
+          echo "Building proxy Docker image..."
+          docker build --compress -t "${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA" proxy/ || { echo 'Docker build for proxy failed'; exit 1; }
+          
+          echo "Pushing proxy Docker image..."
+          docker push "${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA" || { echo 'Docker push for proxy failed'; exit 1; }
 
       - name: Terraform Apply
         env:
